import type { NextPage } from 'next';
import Head from 'next/head';
import VideoPlayer from '../../src/Components/VideoPlayer';
import VideoPlayerContext from '../../src/Context/VideoPlayerContext/VideoPlayerContext';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VideoPlayerContext>
        <VideoPlayer />
      </VideoPlayerContext>
    </div>
  );
};

export default Home;
