import type { NextPage } from 'next';
import Head from 'next/head';
import Calender from '../../src/Components/Calender';
import CalenderContext from '../../src/Context/CalenderContext';
const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CalenderContext>
				<Calender />
			</CalenderContext>
		</div>
	);
};

export default Home;
