import type { NextPage } from 'next';
import Head from 'next/head';
import Todo from '../src/Components/Todo';
import TodoContext from '../src/Context/TodoContext';
const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<TodoContext>
				<Todo />
			</TodoContext>
		</div>
	);
};

export default Home;
