import type { NextPage } from 'next';
import Head from 'next/head';
import ThreadedComment from '../../src/Components/ThreadedComment';
import CommentContext from '../../src/Context/CommentContext';
const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CommentContext>
				<ThreadedComment />
			</CommentContext>
		</div>
	);
};

export default Home;
